# ARG VERSION=stable
# ARG DEBIAN_FRONTEND=noninteractive
# FROM greenbone/gsad

# FROM node:17-alpine
# ENV NODE_VERSION=node_14.x
# ENV NODE_KEYRING=/usr/share/keyrings/nodesource.gpg
# ENV DISTRIBUTION=bullseye
# ENV YARN_KEYRING=/usr/share/keyrings/yarn.gpg

# RUN apt-get update && \
#     apt-get install -y --no-install-recommends \
#     ca-certificates \
#     curl \
#     gnupg

# RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | gpg --dearmor | tee "$NODE_KEYRING" >/dev/null && \
#     echo "deb [signed-by=$NODE_KEYRING] https://deb.nodesource.com/$NODE_VERSION $DISTRIBUTION main" | tee /etc/apt/sources.list.d/nodesource.list
# RUN curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | gpg --dearmor | tee "$YARN_KEYRING" >/dev/null && \
#     echo "deb [signed-by=$YARN_KEYRING] https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list


# RUN apt-get update && \
#     apt-get install -y --no-install-recommends \
#     nodejs \
#     yarn && \
#     rm -rf /var/lib/apt/lists/*

FROM node:alpine

WORKDIR /client

COPY ./package.json .

# CMD bash;

RUN npm install

COPY . .

# ENTRYPOINT ["tail"]
# CMD ["-f","/dev/null"]
# RUN mkdir /gsa/node_modules/.cache && chmod -R 777 /gsa/node_modules/.cache
# USER node
CMD npm start ;
# CMD gsad --http-only -p 9392 --http-cors="http://127.0.0.1:8080" ; npm start
# CMD bash /usr/local/bin/start-gsad ; npm start

# EXPOSE 8080


