services:
  vulnerability-tests:
    image: mercuryheart/vulnerability-tests
    build:
      context: vulnerability-tests
      dockerfile: Dockerfile
    # healthcheck:
    #   disable: true
    environment:
      STORAGE_PATH: /var/lib/openvas/22.04/vt-data/nasl
    volumes:
      - vt_data_vol:/mnt

  notus-data:
    image: greenbone/notus-data
    volumes:
      - notus_data_vol:/mnt

  scap-data:
    image: mercuryheart/scap-data
    build:
      context: scap-data
      dockerfile: Dockerfile
    volumes:
      - scap_data_vol:/mnt

  cert-bund-data:
    image: mercuryheart/cert-bund-data
    build:
      context: cert-bund-data
      dockerfile: Dockerfile
    volumes:
      - cert_data_vol:/mnt

  dfn-cert-data:
    image: mercuryheart/dfn-cert-data
    build:
      context: dfn-cert-data
      dockerfile: Dockerfile
    volumes:
      - cert_data_vol:/mnt
    depends_on:
      - cert-bund-data

  data-objects:
    image: mercuryheart/data-objects
    build:
      context: data-objects
      dockerfile: Dockerfile
    volumes:
      - data_objects_vol:/mnt

  report-formats:
    image: mercuryheart/report-formats
    build:
      context: report-formats
      dockerfile: Dockerfile
    volumes:
      - data_objects_vol:/mnt
    depends_on:
      - data-objects

  gpg-data:
    image: mercuryheart/gpg-data
    build:
      context: gpg-data
      dockerfile: Dockerfile
    volumes:
      - gpg_data_vol:/mnt

  redis-server:
    image: greenbone/redis-server
    restart: on-failure
    volumes:
      - redis_socket_vol:/run/redis/

  pg-gvm:
    image: greenbone/pg-gvm:stable
    restart: on-failure
    volumes:
      - psql_data_vol:/var/lib/postgresql
      - psql_socket_vol:/var/run/postgresql

  gvmd:
    image: mercuryheart/gvmd:stable
    restart: on-failure
    build:
      context: gvmd
      dockerfile: Dockerfile
    volumes:
      - gvmd_data_vol:/var/lib/gvm
      - scap_data_vol:/var/lib/gvm/scap-data/
      - cert_data_vol:/var/lib/gvm/cert-data
      - data_objects_vol:/var/lib/gvm/data-objects/gvmd
      - vt_data_vol:/var/lib/openvas/plugins
      - psql_data_vol:/var/lib/postgresql
      - gvmd_socket_vol:/run/gvmd
      - ospd_openvas_socket_vol:/run/ospd
      - psql_socket_vol:/var/run/postgresql
    depends_on:
      pg-gvm:
        condition: service_started
      scap-data:
        condition: service_completed_successfully
      cert-bund-data:
        condition: service_completed_successfully
      dfn-cert-data:
        condition: service_completed_successfully
      data-objects:
        condition: service_completed_successfully
      report-formats:
        condition: service_completed_successfully

  # gsa-custome:
  #   image: mercuryheart/gsa-custome:lastest
  #   build:
  #     dockerfile: ./gsa/Dockerfile.prod
  #   ports:
  #     - 9392:80
  #   volumes:
  #     # - ./gsa/:/gsa
  #     - gvmd_socket_vol:/run/gvmd
  #     # depends_on:
  #     #   - gsad

  gsa-custome:
    image: mercuryheart/gsa-custome:lastest
    build:
      context: gsa
      dockerfile: Dockerfile.dev
    ports:
      - 9392:9392
    volumes:
      - ./gsa:/client
      - node_modules_vol:/client/node_modules
      - gvmd_socket_vol:/run/gvmd
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - gsad

  gsad:
    image: mercuryheart/gsad:stable
    build:
      context: gsad
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 9393:9393
    volumes:
      - gvmd_socket_vol:/run/gvmd
      # - ./gsad/:/gsad
      # - cert_data_vol:/var/lib/gvm/cert-data
      # - data_objects_vol:/var/lib/gvm/data-objects/gsad
      # - psql_socket_vol:/var/run/postgresql
    depends_on:
      - gvmd
      # front-end:
      #   image: mercuryheart/frontend:lastest
      #   build: ./frontend
      #   restart: on-failure
      #   ports:
      #     - 3000:3000
      #   volumes:
      #     - ./frontend/:/app
      #     - node_modules_vol:/app/node_modules

  back-end:
    image: mercuryheart/backend:lastest
    build:
      context: backend
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8081:8081
    volumes:
      - gvmd_socket_vol:/run/gvmd
      - ./backend/:/app
    depends_on:
      - gvmd

  ospd:
    image: mercuryheart/ospd-openvas:stable
    restart: on-failure
    init: true
    build:
      context: ospd
      dockerfile: Dockerfile
    hostname: ospd.local
    cap_add:
      - NET_ADMIN # for capturing packages in promiscuous mode
      - NET_RAW # for raw sockets e.g. used for the boreas alive detection
    security_opt:
      - seccomp=unconfined
      - apparmor=unconfined
    # command:
    #   [
    #     "ospd-openvas",
    #     "-f",
    #     "--config",
    #     "/etc/gvm/ospd-openvas.conf",
    #     "--mqtt-broker-address",
    #     "mqtt-broker",
    #     "--notus-feed-dir",
    #     "/var/lib/notus/advisories",
    #     "-m",
    #     "666"
    #   ]
    volumes:
      - gpg_data_vol:/etc/openvas/gnupg
      - vt_data_vol:/var/lib/openvas/plugins
      - notus_data_vol:/var/lib/notus
      - ospd_openvas_socket_vol:/run/ospd
      - redis_socket_vol:/run/redis/
    depends_on:
      redis-server:
        condition: service_started
      gpg-data:
        condition: service_completed_successfully
      vulnerability-tests:
        condition: service_completed_successfully

  mqtt-broker:
    restart: on-failure
    image: greenbone/mqtt-broker
    ports:
      - 1883:1883
    networks:
      default:
        aliases:
          - mqtt-broker
          - broker

  notus-scanner:
    restart: on-failure
    image: greenbone/notus-scanner:stable
    volumes:
      - notus_data_vol:/var/lib/notus
      - gpg_data_vol:/etc/openvas/gnupg
    environment:
      NOTUS_SCANNER_MQTT_BROKER_ADDRESS: mqtt-broker
      NOTUS_SCANNER_PRODUCTS_DIRECTORY: /var/lib/notus/products
    depends_on:
      - mqtt-broker
      - gpg-data
      - vulnerability-tests

  gvm-tools:
    image: greenbone/gvm-tools
    volumes:
      - gvmd_socket_vol:/run/gvmd
      - ospd_openvas_socket_vol:/run/ospd
    depends_on:
      - gvmd
      - ospd

volumes:
  gpg_data_vol:
  scap_data_vol:
  cert_data_vol:
  data_objects_vol:
  gvmd_data_vol:
  psql_data_vol:
  vt_data_vol:
  notus_data_vol:
  psql_socket_vol:
  gvmd_socket_vol:
  ospd_openvas_socket_vol:
  redis_socket_vol:
  node_modules_vol:
  node_modules:
